# These are supported funding model platforms

github: [trinitronx, LyraPhase] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: phasik
#open_collective: # Replace with a single Open Collective username
ko_fi: trinitronx
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: trinitronx
#issuehunt: # Replace with a single IssueHunt username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: lyraphase # Replace with a single Polar username
buy_me_a_coffee: TrinitronX # Replace with a single Buy Me a Coffee username
#otechie: # Replace with a single Otechie username
custom: ['https://paypal.me/JamesCuzella'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
