# Site settings
title: James Cuzella's CV
tag_text: markdown-cv
description: markdown-cv is a simple template to list all your accomplishments in a readable Markdown file. It uses CSS to style your text into a web page and a beautiful looking PDF.

# Build settings
markdown: kramdown
style: jamescuzella
exclude: ["README.md", "LICENSE"]
sass:
  style: compressed
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
