# Site settings
title: James Cuzella's CV
tag_text: markdown-cv
description: markdown-cv is a simple template to list all your accomplishments in a readable Markdown file. It uses CSS to style your text into a web page and a beautiful looking PDF.

# Build settings
markdown: kramdown
style: jamescuzella
exclude:
  - "README.md"
  - "LICENSE"
  - "package.json"
  - "package-lock.json"
  - "postcss.config.js"
sass:
  style: compressed
plugins:
  - "jekyll-sass-converter"
  - "jekyll-postcss-v2"
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
webrick:
  headers:
    Access-Control-Allow-Origin: "*" # Allows requests from any origin
    Access-Control-Allow-Origin: "http://localhost:4000" # Allows requests from a specific origin
    Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
postcss:
#  script: node_modules/.bin/postcss
  config: postcss.config.js
